routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware'=>'auth', 'prefix'=>'admin'], function(){
    Route::get('/', 'Admin\AdminController@index');
    Route::get('/trade', ['as'=>'trade.index', 'uses'=>'Admin\TradeController@index']);
    Route::post('/trade/buy', ['as'=>'trade.buy', 'uses'=>'Admin\TradeController@buyCoin']);
    Route::post('/trade/sell', ['as'=>'trade.sell', 'uses'=>'Admin\TradeController@sellCoin']);
    Route::get('/trade/tickers', 'Admin\TradeController@tickers');
    Route::get('/trade/volume', 'Admin\TradeController@volume');
    Route::get('/trade/balances', 'Admin\TradeController@balances');
    Route::get('/trade/trading-pairs', 'Admin\TradeController@tradingPairs');

    Route::get('/trade/add-api', ['as'=>'api.create', 'uses'=>'Admin\ApiAccessController@create']);
    Route::post('/trade/add-api', ['as'=>'api.store', 'uses'=>'Admin\ApiAccessController@store']);
    Route::get('/trade/edit-api/{id}', ['as'=>'api.edit', 'uses'=>'Admin\ApiAccessController@edit']);
    Route::post('/trade/edit-api', ['as'=>'api.update', 'uses'=>'Admin\ApiAccessController@update']);
    Route::get('/trade/delete-api/{id}', ['as'=>'api.destroy', 'uses'=>'Admin\ApiAccessController@destroy']);

    // Only to TEST
    Route::get('/trade/get-ticker/{pair}', 'Admin\TradeController@getTickerByPair');
    Route::get('/trade/get-orders/{pair}', 'Admin\TradeController@getOrders');
    Route::get('/trade/test', 'Admin\TradeController@apiTest');
    // End Test

    Route::resource('/users', 'Admin\UserController');
    Route::get('/user/show/{id}', ['as'=>'user.show', 'uses'=>'Admin\UserController@show']);
    Route::get('/users/role/{id}', ['as'=>'user.role', 'uses'=>'Admin\UserController@role']);
    Route::post('/users/role/{role}', ['as'=>'user.role.store', 'uses'=>'Admin\UserController@roleStore']);
    Route::delete('/users/role/{user}/{role}', ['as'=>'user.role.destroy', 'uses'=>'Admin\UserController@roleDestroy']);

    Route::get('/roles/permission/{id}', ['as'=>'role.permission', 'uses'=>'Admin\RolesController@permissions']);
    Route::post('/roles/permission/{permission}', ['as'=>'role.permission.store', 'uses'=>'Admin\RolesController@permissionStore']);
    Route::delete('/roles/permission/{role}/{permission}', ['as'=>'role.permission.destroy', 'uses'=>'Admin\RolesController@permissionDestroy']);

    Route::resource('/roles', 'Admin\RolesController');
    Route::resource('/permissions', 'Admin\PermissionsController');
});

app/Role.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    protected $table = 'roles';

    protected $fillable = ['name', 'description'];

    public function users()
    {
        return $this->belongsToMany(User::class);
    }

    public function permissions()
    {
        return $this->belongsToMany(Permission::class, 'role_permission');
    }

    public function addPermission($permission)
    {
        if(is_string($permission)){
            $permission = Permission::where('name', '=', $permission)->firstOrFail();
        }

        if($this->existsPermission($permission)){
            return;
        }

        return $this->permissions()->attach($permission);
    }

    public function existsPermission($permission)
    {
        if(is_string($permission)){
            $permission = Permission::where('name', '=', $permission)->firstOrFail();
        }

        return (boolean) $this->permissions()->find($permission->id);
    }

    public function removePermission($permission)
    {
        if(is_string($permission)){
            $permission = Permission::where('name', '=', $permission)->firstOrFail();
        }

        return $this->permissions()->detach($permission);
    }
}

app/Http/Controllers/Admin/RolesController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Role;
use App\Permission;

class RolesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $roles = Role::all();
        $crumbs = [
            ['url'=> '/admin', 'title' => 'Admin'],
            ['url'=> '', 'title' => 'Roles'],
        ];
        return view('admin.roles.index', compact('roles', 'crumbs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $crumbs = [
            ['url'=> '/admin', 'title' => 'Admin'],
            ['url'=> route('roles.index'), 'title' => 'Roles'],
            ['url'=> '', 'title' => 'Create'],
        ];
        return view('admin.roles.create', compact('crumbs'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if($request['name'] && $request['name'] != "Admin"){
            Role::create($request->all());

            return redirect()->route('roles.index');
        }

        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $role = Role::find($id);

        if($role->name == "Admin"){
            return redirect()->route('roles.index');
        }

        $crumbs = [
            ['url'=> '/admin', 'title' => 'Admin'],
            ['url'=> route('roles.index'), 'title' => 'Roles'],
            ['url'=> '', 'title' => 'Edit'],
        ];
        return view('admin.roles.edit', compact('crumbs', 'role'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if(Role::find($id)->name == "Admin"){
            return redirect()->route('roles.index');
        }

        if($request['name'] && $request['name'] != "Admin"){
            Role::find($id)->update($request->all());
        }

        return redirect()->route('roles.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if(Role::find($id)->name == "Admin"){
            return redirect()->route('roles.index');
        }
        Role::find($id)->delete();
        return redirect()->route('roles.index');
    }

    /* Permissions methods */
    public function permissions($id)
    {
        $role = Role::find($id);
        $permissions = Permission::all();

        $crumbs = [
            ['url'=> '/admin', 'title' => 'Admin'],
            ['url'=> route('roles.index'), 'title' => 'Roles'],
            ['url'=> '', 'title' => 'Permissions']
        ];
        return view('admin.roles.permissions', compact('role', 'permissions', 'crumbs'));
    }

    public function permissionStore(Request $request, $id)
    {
        $role = Role::find($id);
        $data = $request->all();

        if($data['permission'] == 0){
            return redirect()->back();
        }

        $permission = Permission::find($data['permission']);
        $role->addPermission($permission);
        return redirect()->back();
    }

    public function permissionDestroy($id, $permission_id)
    {
        $role = Role::find($id);
        $permission = Permission::find($permission_id);
        $role->removePermission($permission);
        return redirect()->back();
    }
}

resources/views/admin/roles/_form.blade.php
<div class="form-group">
    <label for="name">Role name</label>
    <input type="text" class="form-control" name="name" value="{{ isset($role->name) ? $role->name : '' }}">
</div>

<div class="form-group">
    <label for="description">Description</label>
    <input type="text" class="form-control" name="description" value="{{ isset($role->description) ? $role->description : '' }}">
</div>

resources/views/admin/roles/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">Create Role</div>
        <div class="panel-body">
            @include('admin.includes.breadcrumbs')

        	<div class="col-md-12">
        		<form action="{{ route('roles.store') }}" method="post">

        			{{csrf_field()}}
        			@include('admin.roles._form')

        	        <button class="btn btn-success">Save</button>

        		</form>

        	</div>
        </div>
    </div>

</div>

@endsection

resources/views/admin/roles/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">Edit Role</div>
        <div class="panel-body">
            @include('admin.includes.breadcrumbs')

        	<div class="col-md-12">
        		<form action="{{ route('roles.update', $role->id) }}" method="post">

        			{{csrf_field()}}
                    {{ method_field('PUT') }}
        			@include('admin.roles._form')

        	        <button class="btn btn-success">Update</button>

        		</form>

        	</div>
        </div>
    </div>

</div>

@endsection

resources/views/admin/roles/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">Roles List</div>
        <div class="panel-body">
            @include('admin.includes.breadcrumbs')

            <div class="col-md-12">

                <a href="{{ route('roles.create') }}" class="btn btn-info pull-right" title="Add new role" style="margin-bottom: 5px;"><i class="glyphicon glyphicon-plus"></i></a>

                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Name</th>
                            <th>Description</th>
                            <th>Created At</th>
                            <th class="text-right">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                    @forelse($roles as $role)
                        <tr>
                            <th>{{ $role->id }}</th>
                            <td>{{ $role->name }}</td>
                            <td>{{ $role->description }}</td>
                            <td>{{ $role->created_at }}</td>
                            <td class="text-right">
                                <a href="{{ route('role.permission', $role->id) }}" class="btn btn-primary" title="Permissions"><i class="glyphicon glyphicon-cog"></i></a>
                                @if ($role->name == "Admin")
                                @else
                                    <a href="{{ route('roles.edit', $role->id) }}" class="btn btn-default" title="Edit"><i class="glyphicon glyphicon-pencil"></i></a>
                                    <form action="{{route('roles.destroy',$role->id)}}" method="post">
                                        {{ method_field('DELETE') }}
        								{{ csrf_field() }}
                                        <button class="btn btn-danger" title="Delete"><i class="glyphicon glyphicon-trash"></i></button>
                                    </form>
                                @endif
                            </td>
                        </tr>
                    @empty
                        <p>No data registered</p>
                    @endforelse
                    </tbody>
                </table>
            </div>

        </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/roles/permissions.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">List permissions to {{$role->name}}</div>
                <div class="panel-body">
                   @include('admin.includes.breadcrumbs')

                   <form action="{{route('role.permission.store',$role->id)}}" method="post">
           			    {{ csrf_field() }}
               			<div class="form-group col-md-5">
               				<select name="permission" class="form-control">
                                   <option value="0">Selec an permission</option>
               					@foreach($permissions as $permission)
               					<option value="{{$permission->id}}">{{$permission->name}}</option>
               					@endforeach
               				</select>
               			</div>
           				<button class="btn btn-info col-md-2" title="Add new permission"><i class="glyphicon glyphicon-plus"></i></button>
           		   </form>

                   <div class="col-md-12">
                       <table class="table table-bordered">
                           <thead>
                               <tr>
                                   <th>Permission</th>
           						   <th>Description</th>
                                   <th class="text-right">Actions</th>
                               </tr>
                           </thead>
                           <tbody>
                           @forelse($role->permissions as $permission)
                               <tr>
                                   <td>{{ $permission->name }}</td>
           			               <td>{{ $permission->description }}</td>
                                   <td class="text-right">
                                       <form action="{{route('role.permission.destroy',[$role->id,$permission->id])}}" method="post">
                          					{{ method_field('DELETE') }}
                          					{{ csrf_field() }}
                          					<button title="Delete" class="btn btn-danger"><i class="glyphicon glyphicon-trash"></i></button>
                       					</form>
                                   </td>
                               </tr>
                           @empty
                               <p>No data registered</p>
                           @endforelse
                           </tbody>
                       </table>
                   </div>
             </div>
		</div>
	</div>

@endsection